sudo: false
language: cpp
dist: xenial
compiler:
- if [ $TRAVIS_OS_NAME == linux ]; then g++; fi
- if [ $TRAVIS_OS_NAME == osx ]; then clang; fi

os:
- linux
- osx

install:
- if [ $TRAVIS_OS_NAME == linux ]; then export CXX="g++-5" CC="gcc-5"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

notifications:
 email: false

script:
- make --directory Print
