sudo: required
language: cpp
compiler:
- g++
- clang

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install clang-3.8
- sudo apt-get install -qq g++-5

script:
- sudo make
- sudo make clang
