language: cpp
dist: xenial
compiler: g++

install: export CXX="g++-5"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

notifications:
 email: false

script: make --directory Print
